<?php
return [
    'BE' => [
        'compressionLevel' => '0',
        'debug' => true,
        'disable_exec_function' => 0,
        'installToolPassword' => '$P$Cy0VMMtP2NPonUSsS3mS0ttey8rxp9/',
        'lockSSL' => '0',
        'loginSecurityLevel' => 'rsa',
        'sessionTimeout' => '36000',
        'versionNumberInFilename' => '0',
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8mb4',
                'dbname' => 'hgon',
                'driver' => 'mysqli',
                'host' => 'localhost',
                'initCommands' => 'utf8mb4',
                'password' => 'hgon',
                'user' => 'hgon',
            ],
        ],
    ],
    'EXT' => [
        'extCache' => 0,
        'extConf' => [
            'about' => 'a:0:{}',
            'be_acl' => 'a:2:{s:26:"disableOldPermissionSystem";s:1:"1";s:20:"enableFilterSelector";s:1:"1";}',
            'be_secure_pw' => 'a:7:{s:10:"validUntil";s:6:"1 year";s:14:"passwordLength";s:2:"10";s:13:"lowercaseChar";s:1:"1";s:11:"capitalChar";s:1:"1";s:5:"digit";s:1:"1";s:11:"specialChar";s:1:"1";s:8:"patterns";s:1:"3";}',
            'belog' => 'a:0:{}',
            'beuser' => 'a:0:{}',
            'bm_pdf2content' => 'a:0:{}',
            'context_help' => 'a:0:{}',
            'css_styled_content' => 'a:0:{}',
            'dd_googlesitemap' => 'a:0:{}',
            'extension_builder' => 'a:3:{s:15:"enableRoundtrip";s:1:"1";s:15:"backupExtension";s:1:"1";s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";}',
            'feedit' => 'a:0:{}',
            'felogin' => 'a:0:{}',
            'filemetadata' => 'a:0:{}',
            'fluid_styled_content' => 'a:0:{}',
            'form' => 'a:0:{}',
            'func' => 'a:0:{}',
            'gridelements' => 'a:3:{s:20:"additionalStylesheet";s:0:"";s:19:"nestingInListModule";s:1:"0";s:26:"overlayShortcutTranslation";s:1:"0";}',
            'hgon' => 'a:0:{}',
            'hgon_basic' => 'a:0:{}',
            'hgon_donation' => 'a:0:{}',
            'hgon_payment' => 'a:0:{}',
            'hgon_template' => 'a:0:{}',
            'hgon_workgroup' => 'a:0:{}',
            'impexp' => 'a:0:{}',
            'info' => 'a:0:{}',
            'info_pagetsconfig' => 'a:0:{}',
            'linkvalidator' => 'a:0:{}',
            'lowlevel' => 'a:0:{}',
            'news' => 'a:17:{s:13:"prependAtCopy";s:1:"1";s:6:"tagPid";s:1:"1";s:12:"rteForTeaser";s:1:"0";s:22:"contentElementRelation";s:1:"1";s:21:"contentElementPreview";s:1:"1";s:13:"manualSorting";s:1:"0";s:19:"categoryRestriction";s:0:"";s:34:"categoryBeGroupTceFormsRestriction";s:1:"0";s:19:"dateTimeNotRequired";s:1:"0";s:11:"archiveDate";s:4:"date";s:12:"mediaPreview";s:5:"false";s:20:"advancedMediaPreview";s:1:"1";s:24:"showAdministrationModule";s:1:"1";s:35:"hidePageTreeForAdministrationModule";s:1:"0";s:12:"showImporter";s:1:"0";s:18:"storageUidImporter";s:1:"1";s:22:"resourceFolderImporter";s:12:"/news_import";}',
            'opendocs' => 'a:0:{}',
            'pb_social' => 'a:1:{s:11:"socialfeed.";a:11:{s:6:"devmod";s:1:"1";s:15:"ignoreVerifySSL";s:1:"0";s:9:"facebook.";a:1:{s:4:"api.";a:3:{s:2:"id";s:0:"";s:6:"secret";s:0:"";s:15:"pageaccesstoken";s:0:"";}}s:10:"instagram.";a:1:{s:7:"client.";a:5:{s:2:"id";s:0:"";s:6:"secret";s:0:"";s:8:"callback";s:0:"";s:11:"access_code";s:0:"";s:12:"access_token";s:0:"";}}s:9:"linkedin.";a:2:{s:7:"client.";a:3:{s:3:"key";s:0:"";s:6:"secret";s:0:"";s:12:"callback_url";s:0:"";}s:12:"access_token";s:0:"";}s:10:"pinterest.";a:1:{s:4:"app.";a:3:{s:2:"id";s:0:"";s:6:"secret";s:0:"";s:4:"code";s:0:"";}}s:8:"twitter.";a:2:{s:9:"consumer.";a:2:{s:3:"key";s:25:"ofcr9QLLMje0a5lQuhKaJvkS9";s:6:"secret";s:50:"KK79mSpfUhhXaszuIdvsu0mZKNJuf9UBKGh6u3xuaK3B1Q2iMT";}s:6:"oauth.";a:1:{s:7:"access.";a:2:{s:5:"token";s:50:"1156475750368915458-d9cHPePHr668zxSvXeaXPWO8vBW2vM";s:12:"token_secret";s:45:"3mQTCd1GFc79j6Gwxx8SxigPfdwTIFXP1lBIo8ESzvuzl";}}}s:8:"youtube.";a:1:{s:6:"apikey";s:0:"";}s:6:"vimeo.";a:2:{s:7:"client.";a:2:{s:10:"identifier";s:0:"";s:6:"secret";s:0:"";}s:5:"token";s:0:"";}s:7:"tumblr.";a:3:{s:9:"consumer.";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}s:5:"token";s:0:"";s:12:"token_secret";s:0:"";}s:6:"imgur.";a:1:{s:7:"client.";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}}}',
            'phpunit' => 'a:6:{s:17:"excludeextensions";s:8:"lib, div";s:12:"composerpath";s:0:"";s:13:"selenium_host";s:9:"localhost";s:13:"selenium_port";s:4:"4444";s:16:"selenium_browser";s:8:"*firefox";s:19:"selenium_browserurl";s:0:"";}',
            'realurl' => 'a:7:{s:10:"configFile";s:34:"typo3conf/RealUrlConfiguration.php";s:14:"enableAutoConf";s:1:"0";s:14:"autoConfFormat";s:1:"0";s:17:"segTitleFieldList";s:0:"";s:12:"enableDevLog";s:1:"0";s:10:"moduleIcon";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
            'recycler' => 'a:0:{}',
            'reports' => 'a:0:{}',
            'rkw_alerts' => 'a:0:{}',
            'rkw_authors' => 'a:0:{}',
            'rkw_basics' => 'a:0:{}',
            'rkw_consultant' => 'a:0:{}',
            'rkw_consultants' => 'a:0:{}',
            'rkw_ecosystem' => 'a:0:{}',
            'rkw_etracker' => 'a:0:{}',
            'rkw_events' => 'a:0:{}',
            'rkw_geolocation' => 'a:0:{}',
            'rkw_graphics' => 'a:0:{}',
            'rkw_info_layer' => 'a:0:{}',
            'rkw_lightboxfeatherlight' => 'a:0:{}',
            'rkw_mailer' => 'a:0:{}',
            'rkw_newsletter' => 'a:0:{}',
            'rkw_order' => 'a:0:{}',
            'rkw_page_detector' => 'a:0:{}',
            'rkw_pdf2content' => 'a:0:{}',
            'rkw_projects' => 'a:0:{}',
            'rkw_quickcheck' => 'a:0:{}',
            'rkw_registration' => 'a:0:{}',
            'rkw_related' => 'a:0:{}',
            'rkw_resourcespace' => 'a:0:{}',
            'rkw_rss' => 'a:0:{}',
            'rkw_search' => 'a:0:{}',
            'rkw_soap' => 'a:0:{}',
            'rkw_socialcomments' => 'a:0:{}',
            'rkw_staff' => 'a:0:{}',
            'rkw_survey' => 'a:0:{}',
            'rkw_template' => 'a:0:{}',
            'rkw_test' => 'a:0:{}',
            'rkw_tools' => 'a:0:{}',
            'rkw_watchlist' => 'a:0:{}',
            'rkw_webcheck' => 'a:0:{}',
            'rkw_wepstra' => 'a:0:{}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'rte_ckeditor' => 'a:1:{s:15:"ckeditorVersion";s:6:"latest";}',
            'rx_shariff' => 'a:5:{s:8:"services";s:77:"Facebook, LinkedIn, Reddit, StumbleUpon, Flattr, Pinterest, Xing, AddThis, Vk";s:14:"allowedDomains";s:11:"SERVER_NAME";s:3:"ttl";s:4:"3600";s:15:"facebook_app_id";s:0:"";s:15:"facebook_secret";s:0:"";}',
            'saltedpasswords' => 'a:6:{s:20:"checkConfigurationFE";s:1:"0";s:20:"checkConfigurationBE";s:1:"0";s:3:"FE.";a:5:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";s:1:"0";s:15:"onlyAuthService";s:1:"0";s:12:"updatePasswd";s:1:"1";}s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";s:1:"0";s:15:"onlyAuthService";s:1:"0";s:12:"updatePasswd";s:1:"1";}s:21:"checkConfigurationFE2";s:1:"0";s:21:"checkConfigurationBE2";s:1:"0";}',
            'scheduler' => 'a:5:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";s:30:"listShowTaskDescriptionAsHover";s:1:"1";}',
            'setup' => 'a:0:{}',
            'sg_cookie_optin' => 'a:3:{s:3:"key";s:27:"HCHZBG-ZW19DD-FKX4WA-DIG8LM";s:6:"folder";s:26:"fileadmin/sg_cookie_optin/";s:29:"hideModuleInProductionContext";s:5:"FALSE";}',
            'sr_freecap' => 'a:2:{s:19:"encryptionAlgorithm";s:11:"AES-256-CBC";s:4:"salt";s:64:"cH!swe!retReGu7W6bEDRup7usuDUh9THeD2CHeGE*ewr4n39=E@rAsp7c-Ph@pH";}',
            'static_info_tables' => 'a:1:{s:13:"enableManager";s:1:"0";}',
            'sys_action' => 'a:0:{}',
            'sys_note' => 'a:0:{}',
            'taskcenter' => 'a:0:{}',
            'tstemplate' => 'a:0:{}',
            'typoscript_rendering' => 'a:0:{}',
            'varnish' => 'a:4:{s:17:"instanceHostnames";s:14:"127.0.0.1:9081";s:12:"enableDevLog";s:1:"0";s:22:"alwaysSendTypo3Headers";s:1:"0";s:16:"banRequestMethod";s:3:"BAN";}',
            'version' => 'a:0:{}',
            'vhs' => 'a:1:{s:20:"disableAssetHandling";s:1:"0";}',
            'viewpage' => 'a:0:{}',
            'wizard_crpages' => 'a:0:{}',
            'wizard_sortpages' => 'a:0:{}',
            'workspaces' => 'a:0:{}',
            'yoast_seo' => 'a:0:{}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'de',
            ],
        ],
    ],
    'FE' => [
        'addRootLineFields' => '',
        'cHashExcludedParameters' => 'L, v, type, pk_campaign, pk_kwd, utm_source, utm_medium, utm_campaign, utm_term, utm_content',
        'cookieDomain' => '',
        'debug' => true,
        'disableNoCacheParameter' => '1',
        'loginSecurityLevel' => 'normal',
        'pageNotFoundOnCHashError' => false,
        'pageNotFound_handling' => 'USER_FUNCTION:HGON\\HgonTemplate\\UserFunctions\\PageNotFound->pageNotFound',
    ],
    'GFX' => [
        'gdlib_png' => '1',
        'jpg_quality' => '90',
        'processor' => 'ImageMagick',
        'processor_allowTemporaryMasksAsPng' => '',
        'processor_colorspace' => 'sRGB',
        'processor_effects' => '0',
        'processor_enabled' => '1',
        'processor_path' => '/usr/bin/',
        'processor_path_lzw' => '/usr/bin/',
    ],
    'HTTP' => [],
    'INSTALL' => [
        'wizardDone' => [
            'TYPO3\CMS\Install\Updates\BackendUserStartModuleUpdate' => 1,
            'TYPO3\CMS\Install\Updates\Compatibility6ExtractionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FileListIsStartModuleUpdate' => 1,
            'TYPO3\CMS\Install\Updates\FilesReplacePermissionUpdate' => 1,
            'TYPO3\CMS\Install\Updates\MigrateMediaToAssetsForTextMediaCe' => 1,
            'TYPO3\CMS\Install\Updates\MigrateShortcutUrlsAgainUpdate' => 1,
            'TYPO3\CMS\Install\Updates\ProcessedFileChecksumUpdate' => 1,
            'TYPO3\CMS\Install\Updates\WorkspacesNotificationSettingsUpdate' => 1,
        ],
    ],
    'MAIL' => [
        'defaultMailFromAddress' => 'maximilian@faesslerweb.de',
        'defaultMailFromName' => 'HGON',
        'transport' => 'mail',
        'transport_sendmail_command' => '',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
    'SYS' => [
        'BE/debug' => '1',
        'FE/debug' => '1',
        'UTF8filesystem' => '1',
        'caching' => [
            'cacheConfigurations' => [
                'extbase_object' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\ApcBackend',
                ],
            ],
        ],
        'cookieDomain' => '',
        'cookieSecure' => '0',
        'devIPmask' => '*',
        'displayErrors' => 1,
        'enableDeprecationLog' => 'file',
        'encryptionKey' => 'WhatSoEver',
        'errorHandlerErrors' => 32759,
        'exceptionalErrors' => 28674,
        'sitename' => 'HGON',
        'sqlDebug' => 1,
        'systemLocale' => 'de_DE.UTF-8',
        'systemLog' => 'mail,maximilian@faesslerweb.de,4',
        'systemLogLevel' => 0,
        'trustedHostsPattern' => '.*',
    ],
];
